.read lab12.sql

-- Q5
CREATE TABLE greatstudents AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";

-- Q6
CREATE TABLE sevens AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";

-- Q7
CREATE TABLE fa17favnum AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE fa17favpets AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp18favpets AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp18dog AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp18alldogs AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE obedienceimages AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";

-- Q8
CREATE TABLE smallest_int_count AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";
